### ISSUE TITLE
I use ths command " composer require typicms/News"    error:

### ISSUE THREAD

**Issue by veeki** [TypiCMS/News#22]
Composer\Downloader\TransportException]
  The "https://api.github.com/repos/TypiCMS/croppa" file could not be downloa
  ded: failed to open stream: Connection refused

**Comment by sdebacker** [comment]
I'm not sure what could cause this problem, according to this thread, it could be an antivirus : https://stackoverflow.com/questions/43996782/how-to-correct-the-composer-downloader-transportexception-error-for-composer.
